version: '3.7'

services:
  postgres-16:
    container_name: postgres-16
    build: .
    restart: always
    volumes:
      - /docker/storage/storage-postgres-16:/var/lib/postgresql/data
    networks:
      - docker-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD-POSTGRES

networks:
  docker-net:
    external:
      name: docker-lan