version: '3.7'

services:
  postgres-13:
    container_name: postgres-13
    build: .
    restart: always
    volumes:
      - /docker/storage/storage-postgres-13:/var/lib/postgresql/data
    networks:
      - docker-net
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD-POSTGRES

networks:
  docker-net:
    external:
      name: docker-lan